CREATE TABLE Employee(
Id INT NOT NULL IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
GovermentId CHAR(10) NULL,
DateOfBirth DATE NOT NULL,
Department VARCHAR(10) NULL
)